apiVersion: v1
data:
  application.yml: |
    spring:
      cache:
        type: redis
      redis:
        host: {{.Values.productservice.redis.host}}
        port: {{.Values.productservice.redis.port}}
        password: {{.Values.productservice.redis.password}}
      jpa:
        hibernate:
          ddl-auto: validate
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQL81Dialect
            show_sql: true
      datasource:
        url: {{.Values.productservice.postgresql.url}}
        username: {{.Values.productservice.postgresql.username}}
        password: {{.Values.productservice.postgresql.password}}
      jackson:
        property-naming-strategy: SNAKE_CASE

    logging:
      level:
        org:
          postgresql: DEBUG
          hibernate:
            SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: application-properties-product
