apiVersion: v1
kind: Service
metadata:
  name: product-service-service
  labels:
    run: product-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: product-service
