spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: gamestorepassword
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: gamestoreuser
    password: gamestorepassword
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    org:
      postgresql: DEBUG
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
