version: '3.1'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: gamestoreuser
      POSTGRES_PASSWORD: gamestorepassword
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  redis-db:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: '--requirepass gamestorepassword'