openapi: 3.0.3
info:
  title: UserService
  description: UserService
  version: 0.1.0
servers:
  - url: 'https://localhost:8080/api/v1/users'
paths:
  /register:
    post:
      summary: Registration of new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
      responses:
        200:
          description: User successfully created
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    description: uuid
                    type: string
  /login:
    post:
      summary: Retrieving session token with user login/password data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
      responses:
        200:
          description: Successfully login in
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
  /guest_id:
    get:
      summary: Retrieving session token for unregistered guest
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string

components:
  schemas:
    UserData:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string




  
