openapi: 3.0.3
info:
  title: PromotionService
  description: PromotionService
  version: 0.1.0
servers:
  - url: 'https://localhost:8080/api/v1/promotions'
paths:
  /search:
    get:
      summary: Return list of promotions for provided locations
      parameters:
        - in: path
          name: locations
          schema:
            type: array
            items:
              type: string
          required: true
          description: list of locations names
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"

components:
  schemas:
    SearchResponse:
      type: object
      required:
        - collection_promotion
        - product_promotion
      properties:
        collection_promotion:
          type: array
          items:
            $ref: "#/components/schemas/CollectionPromotion"
        product_promotion:
          type: array
          items:
            $ref: "#/components/schemas/ProductPromotion"

    ProductPromotion:
      type: object
      required:
        - id
        - title
        - description
        - multimedia
        - product_id
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        location:
          type: string
        multimedia:
          type: array
          items:
            $ref: "#/components/schemas/Multimedia"
        sale:
          type: number
        product_id:
          type: integer

    CollectionPromotion:
      type: object
      required:
        - id
        - title
        - description
        - multimedia
        - products
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        location:
          type: string
        multimedia:
          type: array
          items:
            $ref: "#/components/schemas/Multimedia"
        products:
          type: array
          maxLength: 10
          items:
            type: object
            required:
              - product
            properties:
              product:
                $ref: "../ProductService/api.yaml#/components/schemas/ProductPreviewDTO"
              sale:
                type: number

    Multimedia:
      title: Multimedia
      description: Single multimedia item representation entity
      required:
        - width
        - height
        - type
        - src
      properties:
        width:
          type: integer
        height:
          type: integer
        type:
          type: string
          enum:
            - img
            - video
        src:
          type: string



  
